
package empleados;

import java.awt.Image;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;


public class GUIEmpleados2 extends javax.swing.JFrame {
    
    ImageIcon fondoEmpleado, imagenEmpleado;
    ImageIcon fondoRegistro, imagenRegistro;
    
     int contador =0;
    String [][] empleados;
    DefaultTableModel modeloTabla;
    ArrayList<Empleado> listaEmpelados = new ArrayList();
    DefaultComboBoxModel modeloComboBoxEmpleados = new DefaultComboBoxModel();
    //DefaultComboBoxModel modeloComboBoxRegistro = new DefaultComboBoxModel();
    String [][] registros;
    DefaultTableModel modeloTabla2;
    

    /**
     * Creates new form GUIEmpelados2
     */
    public GUIEmpleados2() {
        initComponents();
        
        //Esto... no le pares bola, solo es para añadir una imagen de fondo:
        fondoEmpleado = new ImageIcon(getClass().getResource("/imagenes/Sasuke.jpg"));
        imagenEmpleado = new ImageIcon(fondoEmpleado.getImage().getScaledInstance(labelFondo.getWidth(), labelFondo.getHeight(), Image.SCALE_DEFAULT));
        labelFondo.setIcon(imagenEmpleado);
        
        
         fondoRegistro = new ImageIcon(getClass().getResource("/imagenes/Itachi.gif"));
        imagenRegistro = new ImageIcon(fondoRegistro.getImage().getScaledInstance(labelRegistros.getWidth(), labelRegistros.getHeight(), Image.SCALE_DEFAULT));
        labelRegistros.setIcon(imagenRegistro);
        
        //Tabla Empleado
       String[] titulosTablaEmpleado = new String[]{"#Lista","Apellido","Nombre","Cargo"};
       modeloTabla = new DefaultTableModel(empleados, titulosTablaEmpleado);
       tableEmpleado.setModel(modeloTabla);
       
       String[] cargosEmpleado = new String[]{"Gerente","Secretaria","Chofer"};
       
       for(int i = 0; i<cargosEmpleado.length; i++){ 
           modeloComboBoxEmpleados.addElement(cargosEmpleado[i]);
           
       }
       /*
       modeloComboBoxEmpleados.addElement("Gerente");
       modeloComboBoxEmpleados.addElement("Secretaria");
       modeloComboBoxEmpleados.addElement("Chofer");
       */
      comboBoxCargo.setModel(modeloComboBoxEmpleados);
       
       
       
       
       String[] titulosTablaRegistros = new String[]{"#Lista", "Nombre", "Apellido", "Cargo"};
       modeloTabla2 = new DefaultTableModel(registros,titulosTablaRegistros);
       tableRegistro.setModel(modeloTabla2);
        
       
       comboBoxRegistro.setModel(modeloComboBoxEmpleados);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelEmpleados = new javax.swing.JPanel();
        labelNombre = new javax.swing.JLabel();
        labelAoellido = new javax.swing.JLabel();
        labelCargo = new javax.swing.JLabel();
        textNombre = new javax.swing.JTextField();
        textApellido = new javax.swing.JTextField();
        comboBoxCargo = new javax.swing.JComboBox();
        buttonRegistrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableEmpleado = new javax.swing.JTable();
        labelFondo = new javax.swing.JLabel();
        panelRegistro = new javax.swing.JPanel();
        labelFiltrarCargo = new javax.swing.JLabel();
        comboBoxRegistro = new javax.swing.JComboBox();
        buttonFiltrar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableRegistro = new javax.swing.JTable();
        labelRegistros = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelEmpleados.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelNombre.setText("Nombre:");
        panelEmpleados.add(labelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 37, -1, -1));

        labelAoellido.setText("Apellido:");
        panelEmpleados.add(labelAoellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 80, -1, -1));

        labelCargo.setText("Cargo:");
        panelEmpleados.add(labelCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 122, -1, -1));
        panelEmpleados.add(textNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 31, 100, -1));
        panelEmpleados.add(textApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 77, 100, -1));

        comboBoxCargo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelEmpleados.add(comboBoxCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 119, 100, -1));

        buttonRegistrar.setText("Registrar");
        buttonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRegistrarActionPerformed(evt);
            }
        });
        panelEmpleados.add(buttonRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 168, -1, -1));

        tableEmpleado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tableEmpleado);

        panelEmpleados.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 209, 235, 118));
        panelEmpleados.add(labelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 390));

        jTabbedPane1.addTab("Empleado", panelEmpleados);

        panelRegistro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelFiltrarCargo.setText("Filtrar cargo");
        panelRegistro.add(labelFiltrarCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 41, -1, -1));

        comboBoxRegistro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBoxRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxRegistroActionPerformed(evt);
            }
        });
        panelRegistro.add(comboBoxRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 41, -1, -1));

        buttonFiltrar.setText("Aceptar");
        buttonFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFiltrarActionPerformed(evt);
            }
        });
        panelRegistro.add(buttonFiltrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 90, -1, -1));

        tableRegistro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tableRegistro);

        panelRegistro.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 166, 312, 188));
        panelRegistro.add(labelRegistros, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 370));

        jTabbedPane1.addTab("Registro", panelRegistro);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRegistrarActionPerformed
        // TODO add your handling code here:
       
        
        String nombre = textNombre.getText();
        String apellido = textApellido.getText();
        String cargoSeleccionado = (String) comboBoxCargo.getSelectedItem();
        
        Empleado trabajador = new Empleado(nombre,apellido,cargoSeleccionado );
        listaEmpelados.add(trabajador);
        
        contador++;
        String contadorToString = String.valueOf(contador);
        
        modeloTabla.addRow(new String[]{contadorToString ,nombre,apellido,cargoSeleccionado} );
        tableEmpleado.setModel(modeloTabla);
        
    }//GEN-LAST:event_buttonRegistrarActionPerformed

    private void buttonFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFiltrarActionPerformed
        // TODO add your handling code here:
        
        String cargoFiltrado = (String) comboBoxRegistro.getSelectedItem();
        
        System.out.println("Cargo filtrado:"+cargoFiltrado);
     
        for(Empleado item: listaEmpelados){
            
            if(cargoFiltrado.equals("Gerente")){
            
                if(item.getCargo().equals("Gerente")){
                                  modeloTabla2.addRow(new String[]{item.getApellido() ,item.getNombre(), item.getCargo()} );

                }
                
            }
            
            if(cargoFiltrado.equals("Secretaria")){
            
                  modeloTabla2.addRow(new String[]{item.getApellido() ,item.getNombre(), item.getCargo()} );
                
            }
        
        }
        
        
        
        
    }//GEN-LAST:event_buttonFiltrarActionPerformed

    private void comboBoxRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxRegistroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIEmpleados2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIEmpleados2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIEmpleados2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIEmpleados2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIEmpleados2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonFiltrar;
    private javax.swing.JButton buttonRegistrar;
    private javax.swing.JComboBox comboBoxCargo;
    private javax.swing.JComboBox comboBoxRegistro;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labelAoellido;
    private javax.swing.JLabel labelCargo;
    private javax.swing.JLabel labelFiltrarCargo;
    private javax.swing.JLabel labelFondo;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelRegistros;
    private javax.swing.JPanel panelEmpleados;
    private javax.swing.JPanel panelRegistro;
    private javax.swing.JTable tableEmpleado;
    private javax.swing.JTable tableRegistro;
    private javax.swing.JTextField textApellido;
    private javax.swing.JTextField textNombre;
    // End of variables declaration//GEN-END:variables
}
